name: Release CI

on: [push]

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/dist'

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.0

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run build
          npx auto shipit
